<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components2\**" />
    <Content Remove="Components2\**" />

    <EmbeddedResource Remove="Components2\**" />

    <None Remove="Components2\**" />

  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\Country - Copy.cs" />
    <Compile Remove="Data\IDataService.cs" />
    <Compile Remove="Data\LocalDataService.cs" />
    <Compile Remove="Data\SeedData.cs" />
    <Compile Remove="Models\RequirementTypeVM.cs" />
  </ItemGroup>

	<ItemGroup>
		<Content Remove="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>	
	
  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="3.4.0" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="ColorCode.HTML" Version="2.0.15" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Tabler.Blazor" Version="0.0.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Masters\Admin\ManageUsers\" />
    <Folder Include="Pages\Masters\Admin\ManageTickets\" />
    <Folder Include="Pages\BL\Tickets\Templates\" />
    <Folder Include="Pages\Identity\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TabBlazor\TabBlazor.csproj" />
  </ItemGroup>

</Project>
