<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

	<ItemGroup>
		<Content Remove="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>	
	
  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="3.4.0" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="ColorCode.HTML" Version="2.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="TabBlazor" Version="0.12.0-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Masters\Admin\ManageUsers\" />
    <Folder Include="Pages\Masters\Admin\ManageTickets\" />
    <Folder Include="Pages\BL\Tickets\Movility\" />
    <Folder Include="Pages\BL\Tickets\Commons\" />
    <Folder Include="Pages\BL\Tickets\Templates\" />
    <Folder Include="Pages\Identity\" />
    <Folder Include="Pages\Shared\" />
  </ItemGroup>

</Project>
