// <auto-generated />
using System;
using IRIS.Conecta.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRIS.Conecta.Persistence.Migrations
{
    [DbContext(typeof(IRISConectaDatabaseContext))]
    [Migration("20241001003951_cambiosDiego")]
    partial class cambiosDiego
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Department");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyId");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Departments");

                    b.HasIndex(new[] { "DepartmentName" }, "IX_Departments_DepartmentName")
                        .IsUnique();

                    b.HasIndex(new[] { "FacultyId" }, "IX_Departments_FacultyId_Name");

                    b.HasIndex(new[] { "Id" }, "IX_Departments_Id")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Faculties");

                    b.HasIndex(new[] { "FacultyName" }, "IX_Faculties_Name")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_RequestTypes");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Id" }, "IX_RequestTypeId")
                        .IsUnique();

                    b.HasIndex(new[] { "RequestName" }, "IX_RequestTypes_DepartmentId_Name");

                    b.ToTable("RequestTypes", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.TemplateResponses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TemplateName");

                    b.HasKey("Id")
                        .HasName("PK_TemplateResponses");

                    b.HasIndex(new[] { "Id" }, "IX_TemplateResponses_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "RequestTypeId" }, "IX_TemplateResponses_RequestTypeId");

                    b.ToTable("TemplateResponses");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK_Departments_Faculties_FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.RequestType", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Department", "Department")
                        .WithMany("RequestTypes")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestTypes_Departments_DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.TemplateResponses", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.RequestType", "RequestType")
                        .WithMany("TemplateResponses")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_TemplateResponses_RequestsType_RequestTypeId");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.Navigation("RequestTypes");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.RequestType", b =>
                {
                    b.Navigation("TemplateResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
