// <auto-generated />
using System;
using IRIS.Conecta.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRIS.Conecta.Persistence.Migrations
{
    [DbContext(typeof(IRISConectaDatabaseContext))]
    partial class IRISConectaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressResidence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("BornCityId")
                        .HasColumnType("int")
                        .HasColumnName("BornCityId");

                    b.Property<int>("BornCountryId")
                        .HasColumnType("int")
                        .HasColumnName("BornCountryId");

                    b.Property<int>("BornStateId")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CityResidenceId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DocumentNumber");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("DocumentType");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ResidenceCityId")
                        .HasColumnType("int")
                        .HasColumnName("ResidenceCityId");

                    b.Property<int>("ResidenceStateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK_PersonalData");

                    b.HasIndex("BornCityId");

                    b.HasIndex("BornCountryId");

                    b.HasIndex("BornStateId");

                    b.HasIndex("CityResidenceId");

                    b.HasIndex("ResidenceStateId");

                    b.HasIndex(new[] { "DocumentNumber" }, "IX_PersonalData_DocumentNumber");

                    b.HasIndex(new[] { "DocumentType" }, "IX_PersonalData_DocumentType");

                    b.HasIndex(new[] { "FullName" }, "IX_PersonalData_Fullname");

                    b.HasIndex(new[] { "Id" }, "IX_PersonalData_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_PersonalData_UserId");

                    b.ToTable("PersonalData", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.City", "BornCity")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCityId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Cities_BornCityId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Country", "BornCountry")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCountryId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Countries_BornCountryId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "BornState")
                        .WithMany()
                        .HasForeignKey("BornStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.City", "CityResidence")
                        .WithMany()
                        .HasForeignKey("CityResidenceId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "StateResidence")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("ResidenceStateId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_States_ResidenceStateId");

                    b.Navigation("BornCity");

                    b.Navigation("BornCountry");

                    b.Navigation("BornState");

                    b.Navigation("CityResidence");

                    b.Navigation("StateResidence");
                });

           
#pragma warning restore 612, 618
        }
    }
}
