// <auto-generated />
using System;
using IRIS.Conecta.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRIS.Conecta.Persistence.Migrations
{
    [DbContext(typeof(IRISConectaDatabaseContext))]
    partial class IRISConectaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.AcademicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCredit")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrolledSemester")
                        .HasColumnType("int")
                        .HasColumnName("EnrolledSemester");

                    b.Property<bool>("IsInstitutionalGroup")
                        .HasColumnType("bit")
                        .HasColumnName("InstitutionalGroup");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramType")
                        .HasColumnType("int")
                        .HasColumnName("ProgramType");

                    b.Property<string>("ResearchGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResearchGroup");

                    b.Property<string>("ResearchProject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResearchProject");

                    b.Property<int?>("TicketId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("False");

                    b.HasKey("Id")
                        .HasName("PK_AcademicData");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "IX_AcademicData_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramId" }, "IX_AcademicData_ProgramId");

                    b.HasIndex(new[] { "TicketId" }, "IX_AcademicData_TicketIdId");

                    b.HasIndex(new[] { "UserId" }, "IX_AcademicData_UserId");

                    b.ToTable("AcademicData", (string)null);
                });
            

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressResidence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("BornCityId")
                        .HasColumnType("int")
                        .HasColumnName("BornCityId");

                    b.Property<int>("BornCountryId")
                        .HasColumnType("int")
                        .HasColumnName("BornCountryId");

                    b.Property<int>("BornStateId")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CityResidenceId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DocumentNumber");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("DocumentType");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ResidenceCityId")
                        .HasColumnType("int")
                        .HasColumnName("ResidenceCityId");

                    b.Property<int>("ResidenceStateId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("False");

                    b.HasKey("Id")
                        .HasName("PK_PersonalData");

                    b.HasIndex("BornCityId");

                    b.HasIndex("BornCountryId");

                    b.HasIndex("BornStateId");

                    b.HasIndex("CityResidenceId");

                    b.HasIndex("ResidenceStateId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex(new[] { "DocumentNumber" }, "IX_PersonalData_DocumentNumber");

                    b.HasIndex(new[] { "DocumentType" }, "IX_PersonalData_DocumentType");

                    b.HasIndex(new[] { "FullName" }, "IX_PersonalData_Fullname");

                    b.HasIndex(new[] { "Id" }, "IX_PersonalData_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_PersonalData_UserId");

                    b.ToTable("PersonalData", (string)null);
                });
            

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicDataId")
                        .HasColumnType("int");

                    b.Property<string>("AgreementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactData")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalInstitution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAgreement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalDataId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int?>("TicketRequirements")
                        .HasColumnType("int")
                        .HasColumnName("TicketRequirements");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Tickets");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex(new[] { "Id" }, "IX_Ticket_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_Ticket_Status");

                    b.HasIndex(new[] { "Title" }, "IX_Ticket_Title");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.AcademicData", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRIS.Conecta.Domain.Entities.Ticket", "Ticket")
                        .WithOne("AcademicData")
                        .HasForeignKey("IRIS.Conecta.Domain.Entities.AcademicData", "TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicData_Tickets_TicketId");

                    b.Navigation("Program");

                    b.Navigation("Ticket");
                });
          

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.City", "BornCity")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCityId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Cities_BornCityId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Country", "BornCountry")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCountryId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Countries_BornCountryId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "BornState")
                        .WithMany()
                        .HasForeignKey("BornStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.City", "CityResidence")
                        .WithMany()
                        .HasForeignKey("CityResidenceId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "StateResidence")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("ResidenceStateId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_States_ResidenceStateId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Ticket", "Ticket")
                        .WithOne("PersonalData")
                        .HasForeignKey("IRIS.Conecta.Domain.Entities.PersonalData", "TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalData_Tickets_TicketId");

                    b.Navigation("BornCity");

                    b.Navigation("BornCountry");

                    b.Navigation("BornState");

                    b.Navigation("CityResidence");

                    b.Navigation("StateResidence");

                    b.Navigation("Ticket");
                });

            
            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.RequestType", "RequestType")
                        .WithMany("Tickets")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_RequestTypes_RequestTypeId");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("AcademicData")
                        .IsRequired();

                    b.Navigation("PersonalData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
