// <auto-generated />
using System;
using IRIS.Conecta.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRIS.Conecta.Persistence.Migrations
{
    [DbContext(typeof(IRISConectaDatabaseContext))]
    partial class IRISConectaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.AcademicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCredit")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrolledSemester")
                        .HasColumnType("int")
                        .HasColumnName("EnrolledSemester");

                    b.Property<bool>("IsInstitutionalGroup")
                        .HasColumnType("bit")
                        .HasColumnName("InstitutionalGroup");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramType")
                        .HasColumnType("int")
                        .HasColumnName("ProgramType");

                    b.Property<string>("ResearchGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResearchGroup");

                    b.Property<string>("ResearchProject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResearchProject");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("False");

                    b.HasKey("Id")
                        .HasName("PK_AcademicData");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "IX_AcademicData_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramId" }, "IX_AcademicData_ProgramId");

                    b.HasIndex(new[] { "TicketId" }, "IX_AcademicData_TicketIdId");

                    b.HasIndex(new[] { "UserId" }, "IX_AcademicData_UserId");

                    b.ToTable("AcademicData", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2014, 1, 1, 12, 1, 1, 0, DateTimeKind.Unspecified))
                        .HasColumnName("created_at");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("flag");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_code");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id")
                        .HasName("PK__Cities__3213E83FCFF12A69");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("capital");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("currency_symbol");

                    b.Property<string>("Emoji")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("emoji");

                    b.Property<string>("EmojiU")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("emojiU");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("flag");

                    b.Property<string>("Iso2")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("iso2")
                        .IsFixedLength();

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("iso3")
                        .IsFixedLength();

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nationality");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("native");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("numeric_code")
                        .IsFixedLength();

                    b.Property<string>("Phonecode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phonecode");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("region");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.Property<string>("Subregion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subregion");

                    b.Property<int?>("SubregionId")
                        .HasColumnType("int")
                        .HasColumnName("subregion_id");

                    b.Property<string>("Timezones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timezones");

                    b.Property<string>("Tld")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tld");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translations");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id")
                        .HasName("PK__Countrie__3213E83FA74F3AF0");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Department");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyId");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Departments");

                    b.HasIndex(new[] { "DepartmentName" }, "IX_Departments_DepartmentName")
                        .IsUnique();

                    b.HasIndex(new[] { "FacultyId" }, "IX_Departments_FacultyId_Name");

                    b.HasIndex(new[] { "Id" }, "IX_Departments_Id")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Faculties");

                    b.HasIndex(new[] { "FacultyName" }, "IX_Faculties_Name")
                        .IsUnique();

                    b.ToTable("Faculties", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProgramType")
                        .HasColumnType("int")
                        .HasColumnName("ProgramType");

                    b.HasKey("Id")
                        .HasName("PK_Programs");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Programs_DepartmentId");

                    b.HasIndex(new[] { "Id" }, "IX_Programs_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramName" }, "IX_Programs_ProgramName")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramType" }, "IX_Programs_ProgramType");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FipsCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fips_code");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("flag");

                    b.Property<string>("Iso2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iso2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id")
                        .HasName("PK__states__3213E83F220489F8");

                    b.HasIndex("CountryId");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressResidence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("BornCityId")
                        .HasColumnType("int")
                        .HasColumnName("BornCityId");

                    b.Property<int>("BornCountryId")
                        .HasColumnType("int")
                        .HasColumnName("BornCountryId");

                    b.Property<int>("BornStateId")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");                    

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DocumentNumber");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("DocumentType");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ResidenceCityId")
                        .HasColumnType("int")
                        .HasColumnName("ResidenceCityId");

                    b.Property<int>("ResidenceStateId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("False");

                    b.HasKey("Id")
                        .HasName("PK_PersonalData");

                    b.HasIndex("BornCityId");

                    b.HasIndex("BornCountryId");

                    b.HasIndex("BornStateId");

                    b.HasIndex("ResidenceStateId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex(new[] { "DocumentNumber" }, "IX_PersonalData_DocumentNumber");

                    b.HasIndex(new[] { "DocumentType" }, "IX_PersonalData_DocumentType");

                    b.HasIndex(new[] { "FullName" }, "IX_PersonalData_Fullname");

                    b.HasIndex(new[] { "Id" }, "IX_PersonalData_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_PersonalData_UserId");

                    b.ToTable("PersonalData", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_RequestTypes");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Id" }, "IX_RequestTypeId")
                        .IsUnique();

                    b.HasIndex(new[] { "RequestName" }, "IX_RequestTypes_DepartmentId_Name");

                    b.ToTable("RequestTypes", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.TemplateResponses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TemplateName");

                    b.HasKey("Id")
                        .HasName("PK_TemplateResponses");

                    b.HasIndex(new[] { "Id" }, "IX_TemplateResponses_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "RequestTypeId" }, "IX_TemplateResponses_RequestTypeId");

                    b.ToTable("TemplateResponses", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("NotificationType");

                    b.Property<bool>("SendEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("SendEmail");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Notifications");

                    b.HasIndex(new[] { "Id" }, "IX_Notifications_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "NotificationType" }, "IX_Notifications_NotificationType");

                    b.HasIndex(new[] { "TicketId" }, "IX_Notifications_TicketId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicDataId")
                        .HasColumnType("int");

                    b.Property<string>("AgreementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactData")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("EndDateMovility")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDateRequirement")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalInstitution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAgreement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalDataId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDateMovility")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDateRequirement")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("TicketRequirements")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TicketRequirements");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Tickets");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex(new[] { "Id" }, "IX_Ticket_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_Ticket_Status");

                    b.HasIndex(new[] { "Title" }, "IX_Ticket_Title");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.TicketsView", b =>
                {
                    b.Property<string>("AgreementName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AgreementName");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City");

                    b.Property<string>("ContactData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactData");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Department");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateOnly>("EndDateMovility")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDateRequirement")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventName");

                    b.Property<string>("ExternalInstitution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExternalInstitution");

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FacultyName");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool?>("IsAgreement")
                        .HasColumnType("bit")
                        .HasColumnName("IsAgreement");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManagerFullName");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManagerUserId");

                    b.Property<string>("MovilityType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MovilityType");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<string>("RequestName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequestName");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Results");

                    b.Property<DateOnly>("StartDateMovility")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDateRequirement")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketRequirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TicketRequirements");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<double?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("Total");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.ToTable((string)null);

                    b.ToView("TicketsView", (string)null);
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.AcademicData", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRIS.Conecta.Domain.Entities.Tickets.Ticket", "Ticket")
                        .WithOne("AcademicData")
                        .HasForeignKey("IRIS.Conecta.Domain.Entities.AcademicData", "TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicData_Tickets_TicketId");

                    b.Navigation("Program");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.City", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_cities_countries");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK_cities_states");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK_Departments_Faculties_FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Program", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Department", "Department")
                        .WithMany("Programs")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Programs_Deparments_DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.State", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_states_countries");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.PersonalData", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.City", "BornCity")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCityId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Cities_BornCityId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Country", "BornCountry")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("BornCountryId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_Countries_BornCountryId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "BornState")
                        .WithMany()
                        .HasForeignKey("BornStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();                    

                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.State", "StateResidence")
                        .WithMany("PersonalDatas")
                        .HasForeignKey("ResidenceStateId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalDatas_States_ResidenceStateId");

                    b.HasOne("IRIS.Conecta.Domain.Entities.Tickets.Ticket", "Ticket")
                        .WithOne("PersonalData")
                        .HasForeignKey("IRIS.Conecta.Domain.Entities.PersonalData", "TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonalData_Tickets_TicketId");

                    b.Navigation("BornCity");

                    b.Navigation("BornCountry");

                    b.Navigation("BornState");

                    b.Navigation("StateResidence");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.RequestType", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Masters.Department", "Department")
                        .WithMany("RequestTypes")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestTypes_Departments_DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.TemplateResponses", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.RequestType", "RequestType")
                        .WithMany("TemplateResponses")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_TemplateResponses_RequestsType_RequestTypeId");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.Notifications", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.Tickets.Ticket", "Ticket")
                        .WithMany("Notifications")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Departments_RequestTypes_Id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.Ticket", b =>
                {
                    b.HasOne("IRIS.Conecta.Domain.Entities.RequestType", "RequestType")
                        .WithMany("Tickets")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_RequestTypes_RequestTypeId");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.City", b =>
                {
                    b.Navigation("PersonalDatas");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("PersonalDatas");

                    b.Navigation("States");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Department", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("RequestTypes");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Masters.State", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("PersonalDatas");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.RequestType", b =>
                {
                    b.Navigation("TemplateResponses");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("IRIS.Conecta.Domain.Entities.Tickets.Ticket", b =>
                {
                    b.Navigation("AcademicData")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("PersonalData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
